name: Terragrunt

on:
  push:
    branches:
      - main
    paths:
      - states/**
  workflow_dispatch:

jobs:
  apply:
    name: "Terragrunt"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: 0.36.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terragrunt Apply
        id: tg_apply
        env:
          AWS_DEFAULT_REGION: "eu-central-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACE_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          set -x
          cd states/eu-central-1/production/
          terragrunt run-all apply --terragrunt-non-interactive
